apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Kompose\kompose.exe convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: volcano-api
  name: volcano-api
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Kompose\kompose.exe convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: volcano-api
    spec:
      containers:
      - env:
        - name: MONGO_DB
          value: volcanoapp
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_URL
          value: mongo
        image: volcano-api
        name: volcano-api
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
