apiVersion: apps/v1
kind: Deployment
metadata:
  name: volcano-api
spec:
  selector:
    matchLabels:
      app: volcanos
      side: back
  replicas: 1
  template:
    metadata:
      labels:
        app: volcanos
        side: back
    spec:
      containers:
      - name: volcano-api
        image: benoitsemifir/volcano-api
        env:
          - name: MONGO_URL
            value: "volcano-mongo"
          - name: MONGO_PORT
            value: "27017"
          - name: MONGO_DB
            value: "volcanoapp"
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: 500m