kind: Deployment
apiVersion: apps/v1
metadata:
  name: volcano-api
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: volcanos
      side: back
  template:
    metadata:
      labels:
        app: volcanos
        side: back
    spec:
      containers:
        - name: volcano-api
          image: benoitsemifir/volcano-api
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: MONGO_URL
              value: volcano-mongo
            - name: MONGO_PORT
              value: '27017'
            - name: MONGO_DB
              value: volcanoapp
          resources:
            requests:
              cpu: 500m
              memory: 400Mi
            limits:
              cpu: "1"
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: volcano-api
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: volcanos
    side: back
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
status:
  loadBalancer:
    ingress:
      - ip: 127.0.0.1
