kind: Deployment
apiVersion: apps/v1
metadata:
  name: volcano-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volcanos
      side: front
  template:
    metadata:
      labels:
        app: volcanos
        side: front
    spec:
      containers:
        - name: volcano-app
          image: benoitsemifir/volcano-app:1.3
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 120Mi
            limits:
              cpu: "1"
              memory: 1Gi
---
kind: Service
apiVersion: v1
metadata:
  name: volcano-app
  namespace: default
spec:
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 80
  selector:
    app: volcanos
    side: front
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
